# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078d6acdc5e1fb850d23bc9248a9729d91b5917c9b59082fc405d964f1a51cd54216fa9c73facc814db47f36357b8a45c998544a74a5df67de81d71e4b993be9

test:
  secret_key_base: 21313c783967486b605100967c16e11c833d6ca85333622078368dd50413759ea5c092ba84e95ed863b982cb3c60087746329e6fef4f6e6a57623d384cba950e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
